apiVersion: v1
kind: Service
metadata:
  name: tinybert
  namespace: ml-inference
  labels:
    app: tinybert
spec:
  selector:
    app: tinybert
  ports:
  - name: http
    port: 80
    targetPort: 8000