## minio mode, i.e. standalone or distributed
mode: standalone ## other supported values are "distributed"
replicas: 1

rootUser: "miniouser"
rootPassword: "minioPassword"

resources:
  requests:
    memory: 256Mi

consoleIngress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  path: /
  hosts:
    - console-minio.127.0.0.1.nip.io
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


users:
  ## Username, password and policy to be assigned to the user
  ## Default policies are [readonly|readwrite|writeonly|consoleAdmin|diagnostics]
  ## Add new policies as explained here https://docs.min.io/community/minio-object-store/administration/identity-access-management.html#access-management
  ## NOTE: this will fail if LDAP is enabled in your MinIO deployment
  ## make sure to disable this if you are using LDAP.
  - accessKey: console
    secretKey: console123
    policy: consoleAdmin

persistence:
  enabled: true
  annotations: {}
  existingClaim: ""
  storageClass: ""
  volumeName: ""
  accessMode: ReadWriteOnce
  size: 5Gi