apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul-app
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: consul
      targetRevision: 1.2.0
      helm:
        releaseName: consul
        valueFiles:
          - $values/apps/consul/values.yaml
    - repoURL: git@github.com:k8nishant/argocd-poc.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: consul

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
